version: '3.4'

services:
  productmanager.api:
    build:
      context: src/Product/Product.API
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development